## Problem 1

In [1]:
import pandas as pd

In [2]:
scores=pd.read_csv('data.online.scores.txt', sep='\t',header=None,names=['id','midterm','final'])

In [3]:
scores.midterm.max()

37

In [4]:
scores.midterm.max()

100

In [5]:
scores.midterm.quantile([0.25,0.5,0.75])

0.25    68.0
0.50    77.0
0.75    87.0
Name: midterm, dtype: float64

In [6]:
scores.midterm.mean()

76.715000000000003

In [7]:
scores.midterm.mode()

0    77
1    83
dtype: int64

In [8]:
scores.midterm.var()

173.27905405405409

## Problem 2

In [9]:
normalized_midterm=(scores.midterm-scores.midterm.mean())/scores.midterm.std()

In [10]:
normalized_midterm.var()

0.99999999999999989

In [11]:
(90-scores.midterm.mean())/scores.midterm.std()

1.0092262186886871

In [12]:
scores['midterm'].corr(scores['final'],method='pearson')

0.544424742312412

In [13]:
scores['midterm'].cov(scores['final'])

78.254194194194213

In [40]:
scores['midterm'].std()*scores['final'].std()*scores['midterm'].corr(scores['final'],method='pearson')

78.254194194194199

## Problem 3

In [14]:
58/(120+58+2)

0.32222222222222224

In [15]:
books=pd.read_csv('data.libraries.inventories.txt',sep='\t')

In [16]:
import numpy as np

In [17]:
lib=np.array(books.iloc[:,1:])

In [18]:
from scipy.spatial.distance import pdist

In [19]:
pdist(lib,'minkowski', 1)

array([ 6152.])

In [20]:
pdist(lib,'minkowski', 2)

array([ 715.32789684])

In [21]:
pdist(lib,'chebyshev')

array([ 170.])

In [22]:
pdist(lib, 'cosine')

array([ 0.15859597])

In [23]:
from scipy import stats

In [24]:
stats.entropy(lib[0],lib[1])

0.20708093733159472